[project]
name = "teapot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "lxmf>=0.8.0",
    "rns>=1.0.0",
    "schedule>=1.2.2",
]
